steps:
  - name: gcr.io/k8s-skaffold/skaffold
    args:
      - skaffold
      - build
      - '--interactive=false'
      - '--default-repo=us-central1-docker.pkg.dev/$PROJECT_ID/web-app'
      - '--file-output=artifacts.json'
    dir: app
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args: 
      - '-c'
      - >
        gcloud beta deploy releases create rel-$SHORT_SHA
        --delivery-pipeline=web-app --build-artifacts=artifacts.json
        --source=./
        --region=us-central1
    dir: app
    entrypoint: bash 