apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
    - image: leeroy-web
      context: leeroy-web
    - image: leeroy-app
      context: leeroy-app
  #googleCloudBuild:
  #  projectId: project-id-here
deploy:
  kubectl:
    manifests:
      - leeroy-web/kubernetes/deployment.yaml
      - leeroy-app/kubernetes/deployment.yaml
portForward:
  - resourceType: deployment
    resourceName: leeroy-web
    port: 8080
    localPort: 9000
profiles:
- name: staging
  deploy:
    kubectl:
     manifests:
      - leeroy-web/kubernetes/staging.yaml
      - leeroy-app/kubernetes/staging.yaml
- name: prod
  deploy:
    kubectl:
     manifests:
      - leeroy-web/kubernetes/prod.yaml
      - leeroy-app/kubernetes/prod.yaml