# Cloudbuild pipeline for a build with an image
# that passes the vuln policy
# gcloud builds submit . --config cloudbuild-bad.yaml
steps:
  # Build a 'bad' image
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - -c
      - |
        docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/vulnerable-image/fail-image:latest -f Dockerfile.bad .
    id: build
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |
      docker push us-central1-docker.pkg.dev/$PROJECT_ID/vulnerable-image/fail-image:latest &&
      docker image inspect us-central1-docker.pkg.dev/$PROJECT_ID/vulnerable-image/fail-image:latest --format '{{index .RepoDigests 0}}' > image-digest.txt &&
      cat image-digest.txt
    id: push
  - name: gcr.io/$PROJECT_ID/kritis-signer
    entrypoint: /bin/bash
    args:
    - -c
    - |
      /kritis/signer \
      -v=10 \
      -alsologtostderr \
      -image=$(/bin/cat image-digest.txt) \
      -policy=policy.yaml \
      -kms_key_name=${_KMS_KEY_NAME} \
      -kms_digest_alg=${_KMS_DIGEST_ALG} \
      -note_name=${_NOTE_NAME}
    waitFor: push
    id: vulnsign
# Set these variables in your trigger or directly in the below stanza and uncomment 
substitutions:
    _KMS_KEY_NAME: MISSING_KMS_KEY_NAME 
    _KMS_DIGEST_ALG: MISSING_KMS_DIGEST_ALG 
    _NOTE_NAME: MISSING_NOTE_NAME 
images: ['us-central1-docker.pkg.dev/$PROJECT_ID/vulnerable-image/fail-image:latest']
